const categories=['函数基础','集合与数','图像与坐标',...new Set(CHAPTER_ONE_WORDS.map(w=>w.category)),'其他'];
const seed=[["function", "函数：每个允许的输入，都对应唯一的输出。", "函数基础", "For f(x) = x², f(3) = 9.｜输入 3，输出 9。"], ["domain", "定义域：函数允许输入的所有值组成的集合。", "函数基础", "For f(x) = 1/x, the domain excludes 0.｜1/x 的输入不能是 0。"], ["range", "值域：函数实际能得到的所有输出组成的集合。", "函数基础", "For f: ℝ → ℝ, f(x) = x², the range is [0, ∞).｜平方的实际输出都是非负数。"], ["codomain", "陪域：定义函数时指定的目标集合，包含值域。", "函数基础", "For f: ℝ → ℝ, f(x) = x², the codomain is ℝ.｜目标集合是实数，但不代表每个实数都能输出。"], ["variable", "变量：可以取不同数值的符号，如 x。", "函数基础", "In y = 2x + 1, x and y are variables.｜x 和 y 是变量。"], ["constant", "常量：在当前问题中保持固定的量。", "函数基础", "In y = 2x + 1, 2 and 1 are constants.｜2 和 1 是固定数值。"], ["input", "输入：代入函数的值。", "函数基础", "The input is 3.｜把 x = 3 代入 f(x) = x²。"], ["output", "输出：函数给出的结果。", "函数基础", "The output is 9.｜f(3) = 9，所以输出是 9。"], ["independent variable", "自变量：作为输入的变量，通常记作 x。", "函数基础", "In y = f(x), x is the independent variable.｜x 是输入变量。"], ["dependent variable", "因变量：随自变量取值而确定的变量，通常记作 y。", "函数基础", "In y = 2x, y is the dependent variable.｜x 改变时，y 的值也随之确定。"], ["set", "集合：一些确定对象组成的整体。", "集合与数", "A = {1, 2, 3} is a set.｜A 是由 1、2、3 组成的集合。"], ["element", "元素：集合中的一个对象。", "集合与数", "2 is an element of A = {1, 2, 3}.｜写作 2 ∈ A。"], ["subset", "子集：其中每个元素也属于另一个集合。", "集合与数", "{1, 2} is a subset of {1, 2, 3}.｜写作 {1, 2} ⊆ {1, 2, 3}。"], ["real number", "实数：数轴上的数，包括整数、分数和无理数。", "集合与数", "−2, 1/2 and √2 are real numbers.｜实数集合记作 ℝ。"], ["interval", "区间：数轴上两个端点之间的一段，端点也可延伸到无穷。", "集合与数", "[0, 1] includes both endpoints; (0, 1) excludes them.｜方括号包含端点，圆括号不包含。"], ["graph", "图像：在坐标系中，用点表示函数的输入与输出关系。", "图像与坐标", "The graph of y = x² is a parabola.｜y = x² 的图像是一条抛物线。"], ["coordinate", "坐标：描述点位置的数；平面上常写成 (x, y)。", "图像与坐标", "The point has coordinates (2, 4).｜横坐标为 2，纵坐标为 4。"], ["x-axis", "x 轴：平面直角坐标系中的水平轴。", "图像与坐标", "The x-axis is horizontal.｜x 轴上的点满足 y = 0。"], ["y-axis", "y 轴：平面直角坐标系中的竖直轴。", "图像与坐标", "The y-axis is vertical.｜y 轴上的点满足 x = 0。"], ["slope", "斜率：直线的纵向变化量除以横向变化量。", "图像与坐标", "The line y = 2x + 1 has slope 2.｜x 每增加 1，y 增加 2。"]].map((x,i)=>({id:'beginner-'+i,en:x[0],zh:x[1],category:x[2],example:x[3],done:i<4,seed:true}));
const normalizeTerm=s=>s.split(' / ')[0].trim().toLowerCase();
const knownTerms=new Set(seed.map(w=>normalizeTerm(w.en)));
for(const entry of CHAPTER_ONE_WORDS){const match=seed.find(w=>normalizeTerm(w.en)===normalizeTerm(entry.en));if(match){match.source=entry.source;match.reference=entry.zh+'：'+entry.example;}else if(!knownTerms.has(normalizeTerm(entry.en))){seed.push(entry);knownTerms.add(normalizeTerm(entry.en));}}
const $=id=>document.getElementById(id);let words=seed,selected='全部词汇',editing=null;
const key='calculus-word-bank-v1',curriculumKey='calculus-word-bank-curriculum';
try {
  const saved=JSON.parse(localStorage.getItem(key));
  if(Array.isArray(saved)&&saved.every(w=>w&&typeof w.en==='string'&&typeof w.zh==='string'&&typeof w.id==='string')) {
    const current=localStorage.getItem(curriculumKey);
    words=(current==='beginner-v1'||current==='chapter1-v1'?saved:saved.filter(w=>w.seed!==true)).map(w=>({...w,category:categories.includes(w.category)?w.category:'其他'}));
    const existing=new Set(words.map(w=>normalizeTerm(w.en)));
    for(const entry of seed)if(!existing.has(normalizeTerm(entry.en))){words.push({...entry});existing.add(normalizeTerm(entry.en));}
  }
  localStorage.setItem(key,JSON.stringify(words));
  localStorage.setItem(curriculumKey,'chapter1-v1');
} catch {}
function toast(msg){$('toast').textContent=msg;$('toast').classList.remove('hidden');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').classList.add('hidden'),3000)}
function persist(){try{localStorage.setItem(key,JSON.stringify(words));return true}catch{toast('无法保存：请检查浏览器存储设置。本次修改尚未写入。');return false}}
function node(tag,cls,text){const el=document.createElement(tag);if(cls)el.className=cls;if(text!==undefined)el.textContent=text;return el}
function render(){const nav=$('nav');nav.replaceChildren();['全部词汇',...categories].forEach(cat=>{const b=node('button','nav'+(cat===selected?' active':''),cat);b.setAttribute('aria-pressed',String(cat===selected));b.onclick=()=>{selected=cat;render()};nav.append(b)});$('total').textContent=words.length;const done=words.filter(w=>w.done).length;$('learned').textContent=done;$('remaining').textContent=words.length-done;$('heading').textContent=selected;const q=$('search').value.trim().toLowerCase(),status=$('status').value;const shown=words.filter(w=>(selected==='全部词汇'||w.category===selected)&&(status==='all'||(status==='done'?w.done:!w.done))&&[w.en,w.zh,w.example||''].some(t=>t.toLowerCase().includes(q)));$('count').textContent=shown.length+' 个词汇';const cards=$('cards');cards.replaceChildren();if(!shown.length){cards.append(node('div','empty',words.length?'没有找到匹配词汇，试试其他关键词或分类。':'词库还是空的，添加你的第一个词汇吧。'));return}shown.forEach(w=>{const card=node('article','card'),top=node('div','cardtop');top.append(node('span','badge',w.category),node('span','tag',w.source?'第一章':w.seed?'入门词条':'我的词条'));card.append(top,node('h2','word',w.en),node('p','translation',w.zh),node('p','example',w.example||'还没有例句，可以添加一条自己的笔记。'));if(w.reference)card.append(node('p','reference',w.reference));const bottom=node('div','cardbottom'),edit=node('button','light','编辑'),master=node('button','master'+(w.done?' done':''),w.done?'✓ 已掌握':'标记掌握');edit.setAttribute('aria-label','编辑 '+w.en);edit.onclick=()=>openEditor(w);master.setAttribute('aria-pressed',String(!!w.done));master.onclick=()=>{w.done=!w.done;if(!persist())w.done=!w.done;render()};bottom.append(edit,master);card.append(bottom);cards.append(card)})}
function openEditor(w){editing=w?.id||null;$('modalTitle').textContent=w?'编辑词汇':'添加词汇';$('en').value=w?.en||'';$('zh').value=w?.zh||'';$('category').value=w?.category||(categories.includes(selected)?selected:categories[0]);$('example').value=w?.example||'';$('editor').showModal();$('en').focus()}
categories.forEach(c=>{const o=node('option','',c);o.value=c;$('category').append(o)});$('add').onclick=()=>openEditor();$('cancel').onclick=()=>$('editor').close();$('search').addEventListener('input',render);$('status').addEventListener('change',render);$('form').onsubmit=e=>{e.preventDefault();const en=$('en').value.trim(),zh=$('zh').value.trim();if(!en||!zh){toast('请填写英文词汇和中文释义。');return}const previous=words.map(w=>({...w}));const data={en,zh,category:$('category').value,example:$('example').value.trim(),seed:false};if(editing){Object.assign(words.find(w=>w.id===editing),data)}else{words.unshift({id:crypto.randomUUID(),...data,done:false})}if(!persist()){words=previous;return}selected='全部词汇';$('search').value='';$('status').value='all';$('editor').close();render();toast('词汇已保存')};render();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'search_vocabulary',description:'Search the current mathematics vocabulary bank by English, Chinese or example text.',inputSchema:{type:'object',properties:{query:{type:'string'}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:true},execute(input){if(!input||typeof input.query!=='string')throw new Error('query must be a string');const q=input.query.toLowerCase();return words.filter(w=>[w.en,w.zh,w.example||''].some(t=>t.toLowerCase().includes(q))).map(({en,zh,category,example,done})=>({en,zh,category,example,done}))}})).catch(()=>{})}catch{}}
