const categories=['极限与连续','导数与微分','积分','级数','多元函数','其他'];
const seed=[['limit','极限','极限与连续','The limit of f(x) as x approaches zero is 1.'],['continuity','连续性','极限与连续','Check the continuity of the function at x = 0.'],['convergence','收敛','级数','Determine the convergence of the series.'],['derivative','导数','导数与微分','The derivative represents the instantaneous rate of change.'],['differentiation','求导；微分运算','导数与微分','Find the derivative using implicit differentiation.'],['differential','微分','导数与微分','The differential of y is written as dy.'],['definite integral','定积分','积分','Evaluate the definite integral from 0 to 1.'],['antiderivative','原函数','积分','An antiderivative of 2x is x squared.'],['integration by parts','分部积分法','积分','Use integration by parts to evaluate the integral.'],['Taylor series','泰勒级数','级数','Expand the function as a Taylor series about zero.'],['partial derivative','偏导数','多元函数','Find the partial derivative with respect to x.'],['gradient','梯度','多元函数','The gradient points in the direction of steepest increase.']].map((x,i)=>({id:'seed-'+i,en:x[0],zh:x[1],category:x[2],example:x[3],done:false,seed:true}));
const $=id=>document.getElementById(id);let words=seed,selected='全部词汇',editing=null;const key='calculus-word-bank-v1';try{const saved=JSON.parse(localStorage.getItem(key));if(Array.isArray(saved)&&saved.every(w=>w&&typeof w.en==='string'&&typeof w.zh==='string'&&categories.includes(w.category)&&typeof w.id==='string'))words=saved;}catch{}
function toast(msg){$('toast').textContent=msg;$('toast').classList.remove('hidden');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').classList.add('hidden'),3000)}
function persist(){try{localStorage.setItem(key,JSON.stringify(words));return true}catch{toast('无法保存：请检查浏览器存储设置。本次修改尚未写入。');return false}}
function node(tag,cls,text){const el=document.createElement(tag);if(cls)el.className=cls;if(text!==undefined)el.textContent=text;return el}
function render(){const nav=$('nav');nav.replaceChildren();['全部词汇',...categories].forEach(cat=>{const b=node('button','nav'+(cat===selected?' active':''),cat);b.setAttribute('aria-pressed',String(cat===selected));b.onclick=()=>{selected=cat;render()};nav.append(b)});$('total').textContent=words.length;const done=words.filter(w=>w.done).length;$('learned').textContent=done;$('remaining').textContent=words.length-done;$('heading').textContent=selected;const q=$('search').value.trim().toLowerCase(),status=$('status').value;const shown=words.filter(w=>(selected==='全部词汇'||w.category===selected)&&(status==='all'||(status==='done'?w.done:!w.done))&&[w.en,w.zh,w.example||''].some(t=>t.toLowerCase().includes(q)));$('count').textContent=shown.length+' 个词汇';const cards=$('cards');cards.replaceChildren();if(!shown.length){cards.append(node('div','empty',words.length?'没有找到匹配词汇，试试其他关键词或分类。':'词库还是空的，添加你的第一个词汇吧。'));return}shown.forEach(w=>{const card=node('article','card'),top=node('div','cardtop');top.append(node('span','badge',w.category),node('span','tag',w.seed?'示例词条':'我的词条'));card.append(top,node('h2','word',w.en),node('p','translation',w.zh),node('p','example',w.example||'还没有例句，可以添加一条自己的笔记。'));const bottom=node('div','cardbottom'),edit=node('button','light','编辑'),master=node('button','master'+(w.done?' done':''),w.done?'✓ 已掌握':'标记掌握');edit.setAttribute('aria-label','编辑 '+w.en);edit.onclick=()=>openEditor(w);master.setAttribute('aria-pressed',String(!!w.done));master.onclick=()=>{w.done=!w.done;if(!persist())w.done=!w.done;render()};bottom.append(edit,master);card.append(bottom);cards.append(card)})}
function openEditor(w){editing=w?.id||null;$('modalTitle').textContent=w?'编辑词汇':'添加词汇';$('en').value=w?.en||'';$('zh').value=w?.zh||'';$('category').value=w?.category||(categories.includes(selected)?selected:categories[0]);$('example').value=w?.example||'';$('editor').showModal();$('en').focus()}
categories.forEach(c=>{const o=node('option','',c);o.value=c;$('category').append(o)});$('add').onclick=()=>openEditor();$('cancel').onclick=()=>$('editor').close();$('search').addEventListener('input',render);$('status').addEventListener('change',render);$('form').onsubmit=e=>{e.preventDefault();const en=$('en').value.trim(),zh=$('zh').value.trim();if(!en||!zh){toast('请填写英文词汇和中文释义。');return}const previous=words.map(w=>({...w}));const data={en,zh,category:$('category').value,example:$('example').value.trim(),seed:false};if(editing){Object.assign(words.find(w=>w.id===editing),data)}else{words.unshift({id:crypto.randomUUID(),...data,done:false})}if(!persist()){words=previous;return}selected='全部词汇';$('search').value='';$('status').value='all';$('editor').close();render();toast('词汇已保存')};render();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'search_vocabulary',description:'Search the current mathematics vocabulary bank by English, Chinese or example text.',inputSchema:{type:'object',properties:{query:{type:'string'}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:true},execute(input){if(!input||typeof input.query!=='string')throw new Error('query must be a string');const q=input.query.toLowerCase();return words.filter(w=>[w.en,w.zh,w.example||''].some(t=>t.toLowerCase().includes(q))).map(({en,zh,category,example,done})=>({en,zh,category,example,done}))}})).catch(()=>{})}catch{}}
